### PR TITLE
Add StarCityGames decksheet display option

### PR DESCRIPTION
**Pull request by Nightfirecat**
In addition to adding the StarCityGames decksheet format, a number of
under-the-covers changes occurred to facilitate generalizing the
codebase to allow multiple decksheet layouts. Some of these changes
are as follows:

- Decklist parsing (decklist.js) has been fully re-written. All new
  functions accept parameters (usually optional to resemble previous
  behavior as much as possible) and utilize return values rather than
  modifying global variables to allow more predictable behavior, better
  compatibility between decksheets (individual decksheets can utilize
  the return value as needed), and improve ease of testing. The primary
  reason for rewriting parsing was to utilize full card objects (like
  those stored in the global `cards` array) in decklist layout rather
  than simple name-quantity arrays.
- All extraeneous global variables have been removed. The only two that
  remain are necessary for the validation and PDF update timers to
  function.
- The page layout has been updated to include a second radio selection
  above the decklist preview with options for layouts. Additionally,
  both radio selection lists have had their `name` attributes updated
  for ease of selection.
- Both SCG and WotC PDF layout functions have been re-ordered such that
  copy-pasting text from PDFs displays in a more sane format
- `eslint` directives have been added to main.js and decklist.js to
  minimize errors
- Extra js files have been removed
- (incidental) A font sizing bug in the WotC decklist layout has been
  fixed. (previously if no last name was set, font size was too small)
- (incidental) Centered text is now actually centered in the WotC
  decklist layout

With all that said, there are some other possible features that have not
been included in this PR, such as:

- Section overflow looping. Currently, the SCG decklist caps each
  section at 15 cards, and does not push overflow into further (or
  previous) sections.
- Adding handling of a new GET parameter to select decklist. As there
  was no handling for deck sorting, similarly support was not added for
  decklist choice in this PR.
- Disabling of unused fields in specific layouts. The SCG decksheet
  layout does not use all of the same fields which are used in the WotC
  format. (specifically, it does not make use of the Event Date, Event
  Location, and Deck Designer fields) Current behavior is to simply
  ignore the value of these fields while parsing, but allow further
  changes to the fields.
- Smooth out added images. For some reason, they show up rather jagged,
  despite being downscaled from their source images. This may be related
  to https://github.com/MrRio/jsPDF/issues/762
  Closest example?: https://github.com/MrRio/jsPDF/issues/762#issuecomment-231394181
- Utilize the full-resolution StarCityGames.com logo. Currently, for
  load time consideration, a low-resolution version of the
  StarCityGames.com logo is loaded, though a higher-resolution copy is
  available in the repository. Ideally, this image and others should no
  longer be loaded as base64 strings, but loaded via FileReader or some
  other API.
  Ref: https://stackoverflow.com/a/20285053

Finally, due to the update to parsing, there are some changes to
existing behavior--primarily small changes in behavior of how
unrecognized cards are sorted in lists. As much as possible, the new
parsing code behaves similarly to existing code, with the caveat that
sorting is not necessarily stable, which likely explains the
previously-mentioned sorting discrepancies.

Closes april/decklist#8
Fixes april/decklist#32
Fixes april/decklist#38
Supersedes april/decklist#35
Supersedes april/decklist#39
Supersedes april/decklist#40

### CODE REVIEW

**Comment by Nightfirecat** [comment]
For testing this PR, I've been using variations of the following maindeck and sideboard fields to test a variety of types, colors, unrecognized cards, unparseable lines, duplicate entries, etc. Feel free to use it or use your own testing decks.

Also, this PR is what's available at https://nightfirecat.github.io/decklist

main:

```
1 Lim-Dûl's Vault
1 mother of runes
1 thalia, guardian of thraben
1 snapcaster mage
1 brainstorm
1 thoughtseize
1 inquisition of kozilek
1 lightning bolt
1 pyroblast
1 Tarmogoyf
2x Tarmogoyf
3 [FUT] Tarmogoyf
1 meddling mage
1 kolaghan's command
1 karn liberated
3 underground sea
1 sensei's divining top
15 plains
SB: 1 misty rainforest
Sideboard
1 Tarmogoyf
2 tarmogoof
3 lose hope
```

side:
```
1 liliana of the veil
1liliana of the veil
1liliana of the veil
1 tarmogoof
1 tarmogoof
2 underground sea
5 conflux
1 plains
1 island
1 swamp
1 mountain
1 forest
1 flooded strand
1 polluted delta
1 scalding tarn
1 verdant catacombs
```

**Comment by Nightfirecat** [comment]
@april Could you review this when you have some time?

**Comment by april** [comment]
Thank you so much for the shitton of work that went into this. Sorry for taking so darned long to merge it!

**Comment by april** [comment]
BTW, you mind if I credit you on Twitter?

**Comment by Nightfirecat** [comment]
I'm happy to be credited for it, I'm `@Nightfirecat` there as well.

**Pull request merged**
